apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAppName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.containerPortService }}
      targetPort: {{ .Values.containerTargetPortService }}
  type: {{ .Values.serviceType }}
  